#!/usr/bin/env bash
# shellcheck disable=SC1091,SC2086,SC1001,SC2317
# shellcheck source="$HOME/.bashrc"

## Relay1の場合
grafanaInstall(){
    grafana_path=$(which grafana-server)
    if [[ -z $grafana_path ]]; then
        echo "Grafanaをインストールします..."
        
        cd $HOME
        sudopass=$(InputSudoPass)
        echo "$sudopass" | sudo -S apt install -y prometheus prometheus-node-exporter
        sudo apt-get install -y apt-transport-https software-properties-common
        sudo wget -q -O /usr/share/keyrings/grafana.key https://apt.grafana.com/gpg.key
        echo "deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main" > grafana.list
        sudo mv grafana.list /etc/apt/sources.list.d/grafana.list
        sudo apt update && sudo apt install -y grafana


        sudo systemctl enable grafana-server.service
        sudo systemctl enable prometheus.service
        sudo systemctl enable prometheus-node-exporter.service

        #sudo ufw allow 3000/tcp
        #sudo ufw reload

        echo "Grafanaをインストールしました..."
        echo "マニュアルを参考に設定ファイルを作成してください"
        Gum_OneSelect "戻る"
    else
        echo "Grafanaはすでにインストールされています"
        Gum_OneSelect "戻る"
    fi

}

# ## BP,Relay2以降の場合
prometheusInstall(){
    sudopass=$(InputSudoPass)
    echo "$sudopass" | sudo -S apt install -y prometheus-node-exporter
    sudo systemctl enable prometheus-node-exporter.service
    echo "prometheusをインストールしました..."
}
