#!/bin/bash

MithrilBootStrap(){
  LglayStyle "Mithrilクライアントインストール開始..."
  sleep 2
  #Rustインストール
  sudo apt install -y libssl-dev build-essential m4 jq > /dev/null 2>&1
  cd ${HOME}/git
  mithril_release="$(curl -s https://api.github.com/repos/input-output-hk/mithril/releases/latest | jq -r '.tag_name')"
  wget -q https://github.com/input-output-hk/mithril/releases/download/${mithril_release}/mithril-${mithril_release}-linux-x64.tar.gz -O mithril.tar.gz
  tar zxvf mithril.tar.gz mithril-client > /dev/null 2>&1
  sudo cp mithril-client /usr/local/bin/mithril-client
  sudo chmod +x /usr/local/bin/mithril-client
  rm mithril.tar.gz mithril-client
  mithril-client -V
  DglayStyle "Mithrilクライアントをインストールしました"
  case ${NODE_CONFIG} in
  "mainnet" )
      mithril_network=release-${NODE_CONFIG}
  ;;

  "preview" )
      mithril_network=pre-release-${NODE_CONFIG}
  ;;

  "preprod" )
      mithril_network=release-${NODE_CONFIG}
  ;;

  "sanchonet" )
      mithril_network=testing-${NODE_CONFIG}
  ;;
  esac

  export AGGREGATOR_ENDPOINT="https://aggregator.${mithril_network}.api.mithril.network/aggregator"
  export GENESIS_VERIFICATION_KEY="$(wget -q -O - https://raw.githubusercontent.com/input-output-hk/mithril/main/mithril-infra/configuration/${mithril_network}/genesis.vkey)"
  export ANCILLARY_VERIFICATION_KEY=$(wget -q -O - https://raw.githubusercontent.com/input-output-hk/mithril/main/mithril-infra/configuration/${mithril_network}/ancillary.vkey)
  export NETWORK=${NODE_CONFIG}
  export SNAPSHOT_DIGEST="latest"

  LglayStyle "Mithril-DBスナップショットダウンロード開始..."
  YellowStyle "この作業は30分以上かかる場合があります"
  sleep 2
  mithril-client cardano-db download --download-dir ${NODE_HOME} --include-ancillary latest
  DglayStyle "Mithril-DBスナップショットをダウンロードしました..."
}