#!/usr/bin/env bash
# shellcheck disable=SC1091,SC2086,SC1001,SC2317
# shellcheck source="$HOME/.bashrc"
UbuntuSetup(){

    Header "Ubuntu初期設定"

    sudopass=$(InputSudoPass)
    echo $sudopass | sudo -S -v
    # パッケージ自動更新ツールインストール
    if ! command -v unattended-upgrades &> /dev/null; then
        echo
        echo -e "${YELLOW}セキュリティアップデート自動適用ツール(unattended-upgrades)をインストールします${NC}\n"
        sudo apt install unattended-upgrades -y > /dev/null 2>&1
        sudo DEBIAN_FRONTEND=noninteractive dpkg-reconfigure -f noninteractive unattended-upgrades
        echo -e "${YELLOW}unattended-upgradesをインストールしました${NC}\n"
        sleep 1
    else
        # ON/OFF設定確認
        auto_conf="/etc/apt/apt.conf.d/20auto-upgrades"
        if [ -f "$auto_conf" ]; then
            is_enabled=$(grep -c 'Unattended-Upgrade "1"' "$auto_conf")
        else
            is_enabled=0
        fi

        if [ "$is_enabled" -eq 0 ]; then
            echo
            echo -e "${YELLOW}unattended-upgradesが無効になっています。有効化します${NC}\n"
            sudo bash -c 'cat > /etc/apt/apt.conf.d/20auto-upgrades <<EOF
    APT::Periodic::Update-Package-Lists "1";
    APT::Periodic::Unattended-Upgrade "1";
    EOF'
            echo -e "${GREEN}unattended-upgradesを有効化しました${NC}\n"
        else
            echo -e "${GREEN}unattended-upgradesは既に有効化されています${NC}\n"
        fi
        echo -e "${GREEN}unattended-upgradesは既にインストールされています${NC}\n"
        sleep 1
    fi
    echo "次はブラケットペーストモード無効化に進みます"
    read -p "Enter..." 
    echo

    #ブラケットペーストモードOFF
    echo -e "${YELLOW}ブラケットペーストモードを無効化します${NC}\n"
    sleep 2
    # ~/.inputrc が存在しない場合
    if [ ! -f "$HOME/.inputrc" ]; then
        echo 'set enable-bracketed-paste off' > "$HOME/.inputrc"
        echo "✅ ~/.inputrc を新規作成し、設定を追加しました。"

    # 存在する場合
    elif ! grep -Fxq 'set enable-bracketed-paste off' "$HOME/.inputrc"; then
        echo 'set enable-bracketed-paste off' >> "$HOME/.inputrc"
        echo "✅ ~/.inputrc に設定を追記しました。"
    else
        echo "✅ ブラケットペーストモードは既に無効化されています。"
    fi
    echo


    #デーモン自動再起動回避
    echo -e "${YELLOW}デーモン自動再起動回避設定を確認します${NC}\n"
    sleep 2
    if [[ -e /etc/needrestart/ ]]; then
        echo "\$nrconf{restart} = 'a';" | sudo tee /etc/needrestart/conf.d/50local.conf > /dev/null 2>&1
        echo "\$nrconf{blacklist_rc} = [qr(^cardano-node\\.service$) => 0,];" | sudo tee -a /etc/needrestart/conf.d/50local.conf
        echo "\$nrconf{blacklist_rc} = [qr(^cnode-blocknotify.service$) => 0,];" | sudo tee -a /etc/needrestart/conf.d/50local.conf
        echo -e "${YELLOW}デーモン再起動回避設定を適用しました${NC}\n"
        sleep 1
    else
        echo -e "${GREEN}needrestartはインストールされていません。必要に応じて個別に設定してください。${NC}\n"
    fi
    sleep 1
    echo "次は/dev/shmにtmpfsを設定します"
    read -p "Enter..."
    echo

    #共有メモリ設定強化
    if ! grep -qE '^[^#]*tmpfs[[:space:]]+/dev/shm' /etc/fstab; then
        echo -e "${YELLOW}セキュアな共有メモリ領域設定${NC}"
        echo -e "fstabにtmpfsを設定します\n"
        sleep 2
        echo "tmpfs   /dev/shm    tmpfs   rw,noexec,nosuid,nodev   0 0" | sudo tee -a /etc/fstab
        echo -e "${YELLOW}/dev/shmにtmpfsを設定しました${NC}\n"
        sleep 1
    else
        echo -e "${GREEN}/dev/shmにはすでにtmpfsが設定されています${NC}\n"
        sleep 1
    fi

    echo "次はchronyインストールと設定に進みます"
    read -p "Enter..." 

    # chronyインストール
    echo
    if ! command -v chronyd &> /dev/null; then
        echo -e "${YELLOW}chronyをインストールします${NC}\n"
        sudo apt install chrony -y > /dev/null 2>&1
        echo -e "${YELLOW}chronyをインストールしました${NC}\n"
        sleep 1
    else
        echo -e "${GREEN}chronyは既にインストールされています${NC}\n"
        sleep 1
    fi
    # chrony設定
    echo
    echo -e "${YELLOW}chrony設定を確認します${NC}\n"
    sleep 2
    cat /etc/chrony/chrony.conf | grep "makestep 0.1 -1" > /dev/null 2>&1
    if [ $? -ne 0 ]; then
        echo -e "${YELLOW}標準のchrony設定が適用されています${NC}"
        Gum_Confirm_YesNo "SPOKIT推奨設定を適用しますか?" "Yes" "No"
        if [ $iniSettings = "Yes" ]; then
            cat > $HOME/chrony.conf << EOF
pool time.google.com       iburst minpoll 2 maxpoll 2 maxsources 3 maxdelay 0.3
pool time.facebook.com     iburst minpoll 2 maxpoll 2 maxsources 3 maxdelay 0.3
pool time.euro.apple.com   iburst minpoll 2 maxpoll 2 maxsources 3 maxdelay 0.3
pool time.apple.com        iburst minpoll 2 maxpoll 2 maxsources 3 maxdelay 0.3
pool ntp.ubuntu.com        iburst minpoll 2 maxpoll 2 maxsources 3 maxdelay 0.3

# This directive specify the location of the file containing ID/key pairs for
# NTP authentication.
keyfile /etc/chrony/chrony.keys

# This directive specify the file into which chronyd will store the rate
# information.
driftfile /var/lib/chrony/chrony.drift

# Uncomment the following line to turn logging on.
#log tracking measurements statistics

# Log files location.
logdir /var/log/chrony

# Stop bad estimates upsetting machine clock.
maxupdateskew 5.0

# This directive enables kernel synchronisation (every 11 minutes) of the
# real-time clock. Note that it can’t be used along with the 'rtcfile' directive.
rtcsync

# Step the system clock instead of slewing it if the adjustment is larger than
# one second, but only in the first three clock updates.
makestep 0.1 -1

# Get TAI-UTC offset and leap seconds from the system tz database
leapsectz right/UTC

# Serve time even if not synchronized to a time source.
local stratum 10
EOF
            sudo mv $HOME/chrony.conf /etc/chrony/chrony.conf
            sudo systemctl restart chrony
            echo -e "${YELLOW}chronyを再起動しました${NC}\n"
            sleep 1
        else
            echo -e "${YELLOW}chromeを標準設定で運用します${NC}\n"
            sleep 1
        fi
    else
        echo -e "${GREEN}既にSPOKIT推奨設定が適用されています${NC}\n"
        sleep 1
    fi
    echo "次はssh設定変更に進みます"
    read -p "Enter..."


    # ssh設定変更
    iniSettings=""
    echo -e "${YELLOW}ssh設定を確認します${NC}\n"
    sleep 2

    mkdir -p $HOME/.ssh

    KbdInteractiveAuthentication=$(echo "$sudopass" | sudo -S /usr/sbin/sshd -T | grep -i kbdinteractiveauthentication | awk '{print $2}')
    PasswordAuthentication=$(echo "$sudopass" | sudo -S /usr/sbin/sshd -T | grep -i passwordauthentication | awk '{print $2}')
    PermitRootLogin=$(echo "$sudopass" | sudo -S /usr/sbin/sshd -T | grep -i permitrootlogin | awk '{print $2}')
    PermitEmptyPasswords=$(echo "$sudopass" | sudo -S /usr/sbin/sshd -T | grep -i permitemptypasswords| awk '{print $2}')

    if [[ $KbdInteractiveAuthentication != "no" ]]; then
        echo -e "対話式認証（ワンタイムパスワード・PAMなど）設定"
        echo -e "現在値 ${YELLOW}KbdInteractiveAuthentication: ${RED}$KbdInteractiveAuthentication${NC}\n"
        echo -e "推奨値 ${YELLOW}KbdInteractiveAuthentication:${NC} ${GREEN}no${NC}\n"

        Gum_Confirm_YesNo "KbdInteractiveAuthenticationをNoに変更しますか?" "Yes" "No"
        if [ $iniSettings = "Yes" ]; then
            echo -e "${YELLOW}KbdInteractiveAuthenticationをNoに変更します${NC}\n"
            sudo sed -i '/^#Port 22/i KbdInteractiveAuthentication no' /etc/ssh/sshd_config
        fi
    fi

    if [[ $PasswordAuthentication != "no" ]]; then
        echo -e "パスワード認証設定"
        echo -e "現在値 ${YELLOW}PasswordAuthentication: ${RED}$PasswordAuthentication${NC}"
        echo -e "推奨値 ${YELLOW}PasswordAuthentication:${NC} ${GREEN}no${NC}\n"

        Gum_Confirm_YesNo "PasswordAuthenticationをNoに変更しますか?" "Yes" "No"
        if [ $iniSettings = "Yes" ]; then
            echo -e "${YELLOW}PasswordAuthenticationをNoに変更します${NC}\n"
            sudo sed -i '/^#Port 22/i PasswordAuthentication no' /etc/ssh/sshd_config
        fi
    fi

    if [[ $PermitRootLogin != "no" ]]; then
        echo -e "rootログイン設定"
        echo -e "現在値 ${YELLOW}PermitRootLogin: ${RED}$PermitRootLogin${NC}"
        echo -e "推奨値 ${YELLOW}PermitRootLogin:${NC} ${GREEN}no${NC}\n"

        Gum_Confirm_YesNo "PermitRootLoginをNoに変更しますか?" "Yes" "No"
        if [ $iniSettings = "Yes" ]; then
            echo -e "${YELLOW}PermitRootLoginをNoに変更します${NC}\n"
            sudo sed -i '/^#Port 22/i PermitRootLogin no' /etc/ssh/sshd_config
        fi
    fi

    if [[ $PermitEmptyPasswords != "no" ]]; then
        echo -e "空パスワード許可設定"
        echo -e "現在値 ${YELLOW}PermitEmptyPasswords: ${RED}$PermitEmptyPasswords${NC}"
        echo -e "推奨値 ${YELLOW}PermitEmptyPasswords:${NC} ${GREEN}no${NC}\n"

        Gum_Confirm_YesNo "PermitEmptyPasswordsをNoに変更しますか?" "Yes" "No"
        if [ $iniSettings = "Yes" ]; then
            echo -e "${YELLOW}PermitEmptyPasswordsをNoに変更します${NC}\n"
            sudo sed -i '/^#Port 22/i PermitEmptyPasswords no' /etc/ssh/sshd_config
        fi
    fi

    port_number=$(echo "$sudopass" | sudo -S /usr/sbin/sshd -T | grep -i ^port | awk '{print $2}')
    if [[ $port_number = "22" ]]; then
        echo -e "${GREEN}sshのPort番号は22に設定されています${NC}\n"
        echo -e "${YELLOW}セキュリティの観点からPort番号を変更することを強く推奨します${NC}\n"

        Gum_Confirm_YesNo "Portを変更しますか?" "Yes" "No"
        if [ $iniSettings = "Yes" ]; then
            select_port "ssh"
            echo -e "${YELLOW}sshのPort番号を22から$port_numberに変更します${NC}\n"
            sudo sed -i "s/^#\?Port.*/Port ${port_number}/" /etc/ssh/sshd_config
        fi
        sleep 2
    else
        echo -e "${GREEN}sshのPort番号は${port_number}です${NC}\n"
        sleep 2
    fi

    sudo sshd -t
    if [ $? -ne 0 ]; then
        echo -e "${RED}ssh設定にエラーがあります。設定を確認してください。${NC}"
        exit 1
    fi

    #fail2ban設定
    if command -v fail2ban-client >/dev/null 2>&1; then
        echo "✅ fail2ban はインストールされています。"
    else
        echo "不正アクセス対策ツール"
        echo "❌ fail2ban はインストールされていません。"
        Gum_Confirm_YesNo "fail2banをインストールしますか?" "Yes" "No"
        if [ $iniSettings = "Yes" ]; then
            echo -e "${YELLOW}fail2banをインストールします${NC}\n"
            sudo apt install fail2ban -y > /dev/null 2>&1
        fi
    fi

    # fail2ban設定確認
    if [ ! -s /etc/fail2ban/jail.local ]; then
        sudo tee /etc/fail2ban/jail.local > /dev/null << EOF

[sshd]
enabled = true
port = ${port_number}
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
EOF
        echo -e "${YELLOW}fail2banを設定しました${NC}\n"
        echo -e "ポート番号: ${GRREN}$port_number${NC} をfail2banに設定しました\n"
        sudo systemctl restart fail2ban
        echo -e "${YELLOW}fail2banを再起動しました${NC}\n"
        sleep 1
    else
        echo "✅ fail2ban設定済み"
    fi
    read -p "Enterを押すと続行します..." 
    

    #ufw有効化
    echo -e "${YELLOW}ufwの設定を確認します${NC}\n"
    sleep 1
    echo $sudopass | sudo -S -v
    if [[ $(sudo ufw status | grep -i Status) = "Status: inactive" ]]; then
        echo -e "${YELLOW}ufwが無効になっています${NC}\n"
        echo -e "${YELLOW}セキュリティの観点からufwを有効にすることを強く推奨します${NC}\n"
        echo -e "ただしご利用のVPS側でハードウェアファイアウォールが有効になっている場合は、二重に有効化しないでください\n"
        Gum_Confirm_YesNo "ufwを有効にしますか?" "Yes" "No"
        if [ $iniSettings = "Yes" ]; then
            echo -e "${YELLOW}ufwを有効にします${NC}\n"
            sudo ufw allow ${port_number}/tcp > /dev/null 2>&1
            sudo ufw --force enable > /dev/null 2>&1
            echo -e "sshポート番号: ${GRREN}$port_number${NC} をufwに設定しました\n"
            echo -e "${YELLOW}ufwを有効にしました${NC}\n"
            sleep 1
        else
            echo -e "${YELLOW}ufwの有効化をスキップしました${NC}\n"
            echo -e "${YELLOW}ufwを有効にしていない場合は、VPS側のハードウェアファイアウォールにSSHポート(${GRREN}$port_number${NC})を追加してください${NC}\n"
            echo -e 
            sleep 1
        fi
    else
        sudo ufw allow ${port_number}/tcp > /dev/null 2>&1
        sudo ufw reload > /dev/null 2>&1
        echo -e "sshポート番号: ${GRREN}$port_number${NC} をufwに設定しました\n"
        sleep 1
    fi

    sudo service sshd reload
    clear
    echo -e "ssh設定を変更しました\n"
    echo -e "変更後のsshポート番号:${GREEN}$port_number${NC}\n"
    echo -e "${YELLOW}新しいssh設定で接続確認するためにsshの再接続が必要です${NC}\n"
    echo
    echo -e "${RED}ssh再接続に関する注意事項${NC}\n"
    echo -e "1.現在の接続を維持しながら新しいウィンドウで再接続してください${NC}\n"
    echo -e "2.再接続する際には新しいポート番号${YELLOW}$port_number${NC}に変更してください\n"
    echo -e "ssh鍵認証を使用する場合"
    echo -e "1.${GREEN}$HOME/.ssh${NC}に事前に作成した${YELLOW}authorized_keys${NC}をアップロードしてください\n"
    echo -e "2.接続プロファイルに${YELLOW}ssh_ed25519${NC}を設定して接続してください\n"
    echo -e "3.再接続できない場合はこのウィンドウでSSH設定またはFW設定を確認してください\n"
    echo
    echo -e "新しいウィンドウで再接続できたらこのウィンドウでEnterを押してください${NC}"
    read -p "Enterを押すとセッションを終了します..."
    tmux kill-session -t spokit
}


#Ubuntuセキュリティ設定開始確認
#設定内容列挙
echo -e "${YELLOW}このモードでは以下のUbuntu初期設定を行います${NC}\n"
echo -e "1.セキュリティアップデート自動適用ツール(unattended-upgrade)インストールと有効化"
echo -e "2.ブラケットペーストモード無効化"
echo -e "3.デーモン自動再起動回避設定"
echo -e "4./dev/shmにtmpfsを設定"
echo -e "5.chronyインストールとSPOKIT推奨設定適用"
echo -e "6.ssh設定変更(選択制)"
echo -e "  ・KbdInteractiveAuthentication無効化"
echo -e "  ・PasswordAuthentication無効化"
echo -e "  ・PermitRootLogin無効化"
echo -e "  ・PermitEmptyPasswords無効化"
echo -e "  ・ssh Port番号変更"
echo -e "8.fail2banインストールと設定"
echo -e "9.ufw有効化とsshポート許可設定\n"
sleep 2
Gum_Confirm_YesNo "Ubuntu初期設定を開始しますか?" "Yes" "No"
if [ $iniSettings = "Yes" ]; then
    UbuntuSetup
else
    echo -e "${YELLOW}Ubuntu初期設定をスキップしました${NC}\n"
    sleep 1
fi