name: Build develop test package

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-develop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read version
        id: version
        run: |
          spokit_version=$(cat ./scripts/spokit.library | tr -d '[:space:]')
          echo "spokit_version=$spokit_version" >> $GITHUB_OUTPUT

      - name: Embed version into scripts
        run: bash .github/scripts/embed_version.sh "${{ steps.version.outputs.spokit_version }}"

      - name: Build dist package
        run: |
          mkdir -p dist
          tar --exclude='.git' --exclude='dist' -czvf dist/spokit-develop.tar.gz .

      - name: Commit dist folder
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/
          git commit -m "Auto build: spokit-develop.tar.gz for ${{ steps.version.outputs.spokit_version }}" || true
          git push || true
